### ISSUE TITLE
compressed addresses

### ISSUE THREAD

**Issue by Andy19999999999999** [j4rj4r/Bitcoin-Brainwallet-Bruteforce#2]
Did you think to add compressed addresses? Library 'bit' lets to make it. And why   are you not using 'bit' for getting privatekey?

**Comment by j4rj4r** [comment]
https://github.com/j4rj4r/Bitcoin-Brainwallet-Bruteforce/blob/3e04c1110f2fc7ffd1797974454df57bc34968a8/privatekey.py#L19
Hello, the compressed addresses are already in the code ah ah I just have to add a parameter ^^ It's a personal project at the beginning and I wanted to do this part myself

**Comment by j4rj4r** [comment]
I've updated the script

**Comment by Andy19999999999999** [comment]
Hi, ' main.py -c ' do not works, only ' main.py -c True ' .

сб, 24 апр. 2021 г. в 14:49, Jarjar ***@***.***>:

**Comment by j4rj4r** [comment]
Hi, oups new update ^^
